name = 'alacritty'
tags = [
    'fork',
    'personal',
    'rust',
]

[[remotes]]
name = 'origin'
url = 'ssh://git@github.com/edeneast/alacritty'

[[remotes]]
name = 'upstream'
url = 'https://github.com/alacritty/alacritty.git'
