# Don't print a new line at the start of the prompt
add_newline = false

[character]
symbol = "➜"     # The "symbol" segment is being set to "➜"

[aws]
disabled = true

[conda]
disabled = true

[directory]
truncation_length = 3
style = "bold cyan"

[git_branch]
style = "bold yellow"

[git_state]
progress_divider = " of "
cherry_pick = "🍒 PICKING"
